### ISSUE TITLE
dropdown-content is in incorrect location when paper-menu-button is in an iron-list

### ISSUE THREAD

**Issue by hcarmona** [PolymerElements/paper-menu-button#66] opened 2016-02-18 22:14 UTC
dropdown-content is in incorrect location when paper-menu-button is in an iron-list.

It's expected that using a paper-menu-button in an iron-list behave the same as if it's used several times on a page.

JSBin with undesired behavior:
http://jsbin.com/tikezi/59/edit?html,output

**Comment by cdata** [comment] 2016-02-18 22:18
Hi, thanks for reporting. This is a dupe of https://github.com/PolymerElements/iron-fit-behavior/issues/33, so I'm going to close it.

**Closed by cdata** 2016-02-18 22:18 UTC
