### ISSUE TITLE
The dropdown closes when select an item (in paper-menu with multi selection)

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-menu-button#45] opened 2015-12-07 16:24 UTC
In [the online demo](https://elements.polymer-project.org/elements/paper-menu-button?view=demo) it works well, it doesn't close.
But in the master branch it closes when select an item.

**Comment by Simon-Hohberg** [comment] 2015-12-11 12:40
Just to maybe make your life easier, it seems it breaks with version 1.1.2 of iron-overlay-behavior. Using version 1.0.9 of iron-overlay-behavior it works as expected.

**Comment by manfield** [comment] 2015-12-12 14:36
Ok, same issue with 1.1.1 version of iron-overlay-behavior.
Waiting for resolution, thanks.

**Comment by valdrinkoshi** [comment] 2015-12-15 00:24
The issue is caused by this other issue https://github.com/Polymer/polymer/issues/3201

**Comment by valdrinkoshi** [comment] 2015-12-16 01:14
Closing this as it depends on fix provided in [Polymer/polymer](https://github.com/Polymer/polymer).
The PR https://github.com/Polymer/polymer/issues/3201 got merged, so it will be available in the next polymer version (v1.2.4)

**Closed by valdrinkoshi** 2015-12-16 01:14 UTC

**Comment by abdonrd** [comment] 2015-12-16 09:37
Thanks @valdrinkoshi!
