### ISSUE TITLE
Click on the already selected item should close the menu

### ISSUE THREAD

**Issue by slavko-ptitsyn** [PolymerElements/paper-menu-button#61] opened 2016-02-05 12:14 UTC
Steps to reproduce: 
1. Go https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html&active=paper-menu-button
2. Open first menu 
3. Select "alpha" item
4. Open first menu again
5. Select "alpha" item again
Actual result: the drop down menu not disappear if item is selected
![pmb](https://cloud.githubusercontent.com/assets/16416029/12845999/90c8b03a-cc12-11e5-9f9a-77458e1ded62.png)

Possible solution is to replace iron-select event with iron-activate event here:

` listeners: {
        'iron-select': '_onIronSelect'
},`

As a result, _onIronSelect will be called on every item click.

**Comment by cdata** [comment] 2016-02-09 18:46
Hi, thanks for reporting! I'm going to close this issue because it is a dupe of https://github.com/PolymerElements/paper-dropdown-menu/issues/72.

**Closed by cdata** 2016-02-09 18:46 UTC
