### ISSUE TITLE
Menu not opening on touchscreen tap

### ISSUE THREAD

**Issue by brycethorup** [PolymerElements/paper-menu-button#13] opened 2015-08-05 21:10 UTC
I have a `paper-menu-button` that will open the associated `paper-menu` fine when clicked on with a mouse, but does not when tapped using a touchscreen. The issue is the same in the [catalog demo](https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html). This may be related to #11.

**Comment by aydun1** [comment] 2015-08-12 00:54
I've noticed the same thing.
It appears to register the touch twice.The Dinosaurs menu opens from the left so touching the left of the button also selects the first item and highlights it gray. When touching the right, this second tap is on the menu button, because the menu hasn't expanded to cover that area yet, so the menu closes.

**Comment by kungufli** [comment] 2015-08-25 14:32
+1

**Comment by yetanotherse** [comment] 2015-08-26 05:58
@aydun1 facing the same issue. Works fine using mouse but tap registers as a double-click which selects the first menu item. In my case, it's a link so that link is opened.

**Comment by Sinjins** [comment] 2015-08-27 16:20
+1

**Comment by danbeam** [comment] 2015-08-28 15:41
/cc @cdata 

gonna have to hack around this if we wanna ship the new chrome://downloads using polymer:
https://code.google.com/p/chromium/issues/detail?id=526102

**Comment by intositeme** [comment] 2015-09-09 10:19
Am having a similar issue. The menu opens up and closes. My menu is embedded inside a paper-scroll-header-panel.
On the desktop,  chrome developer toggle devices on, this always happens.
On a mobile, the same thing happens, but if i scroll down and the paper-scroll-header-panel minimises, the dropdown will show up fine.

**Comment by fiws** [comment] 2015-09-16 04:33
This dropdown closes because of `_onCaptureClick`. This bug: https://github.com/PolymerElements/paper-menu-button/issues/13

**Comment by fiws** [comment] 2015-09-16 05:08
`bower install PolymerElements/iron-overlay-behavior#use-tap` (choose ad1cda0070) fixed it for me. Wonder why the branch is not merged...

**Comment by Frexuz** [comment] 2015-09-18 18:59
@fiws thanks, your suggestion fixed it for me. For others; I'm also using `FastClick`. Without it, I did not have this problem.

**Comment by cdata** [comment] 2015-09-22 17:36
Hey guys, thanks for reporting this. As discussed, `PolymerElements/iron-overlay-behavior#use-tap` addresses this bug to some extent, but the branch currently introduces a regression in other areas so it can't be merged as-is.

Can any of you offer device and browser information relevant to the reproduction of this bug?

Thanks!

**Comment by fiws** [comment] 2015-09-23 17:14
@cdata simple example: http://embed.plnkr.co/gy0Snv4Lz68mlvsy1IIx/preview

For me it almost seems like it's almost easier to name touch enabled browsers where this issue does not occur, as I experienced this issue with all of them so far:

Does open and instantly close unless tapping directly on the ↓
* Chrome 45 Desktop (with touch emulation)
* Chrome 45 Mobile
* Chrome Dev 47 Mobile
* Firefox 41 Mobile

Does open and close instantly only when tapping the ↓
* Firefox 41 (touch emulation)

**Comment by cdata** [comment] 2015-09-24 21:16
This has been fix via polymerelements/iron-overlay-behavior#22 - please re-open if the problem seems to stick around!

**Closed by cdata** 2015-09-24 21:16 UTC
Labels: code-yellow

**Comment by kungufli** [comment] 2015-09-25 10:59
Seems resolved for me, thanks.
